# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
         
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
  
      - name: Install dependencies
        uses: bahmutov/npm-install@v1   
        
      - name: Save environment variables
        run:
          echo "VITE_APP_TITLE=${{ secrets.APP_TITLE }}" >> ./.env.production &&
          echo "BASE_URL=${{ secrets.API_URL }}" >> ./.env.production
      
      - name: Test environment variables
        run: cat ./.env.production

      - name: Build project
        run: npm run build
        
      - name: Deploy to Hostinger 
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftp
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}  
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./dist/  